export const Gents = {
    title: "GentsFashion",
    image1: "assets/men/image1.jpg",
    image2: "assets/men/image2.jpg",
    image3: "assets/men/image3.jpg",
    image4: "assets/men/image4.jpg",
    image5: "assets/men/image5.jpg",
    image6: "assets/men/image6.jpg",
    price1: "559 INR",
    price2: "459 INR",
    price3: "659 INR",
    price4: "759 INR",
    price5: "859 INR",
    price6: "959 INR",   
}
export const Ladies = {
    title: "WomenFashion",
    image1: "assets/women/one.jpg",
    image2: "assets/women/two.jpg",
    image3: "assets/women/three.jpg",
    image4: "assets/women/four.jpg",
    image5: "assets/women/five.jpg",
    image6: "assets/women/six.jpg",
    price1: "559 INR",
    price2: "459 INR",
    price3: "659 INR",
    price4: "759 INR",
    price5: "859 INR",
    price6: "959 INR",   
}